Allows the counting of number of records in large file
NASA-PDS/pds4-jparser pull request #39
Opened 2021-04-26 22:51 UTC by qchaupds

* Modify logic to count the number of records in a large file in TableReader.java
Refs:

https://github.com/NASA-PDS/validate/issues#326 File-size check fails for large data files
https://github.com/NASA-PDS/validate/issues#327 validate fails to process large data file

The testing will be done via validate pull request which uses the service of TableReader.java
This pull request should be merged before validate since there is a dependency.

2021-04-26 23:06 UTC, qchaupds commented
Please hold off on merging.   For some strange reason, validate regression test is hanging.  Trying to figure out who is the culprit.

2021-04-28 03:39 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/objectAccess/TableReader.java
> +    private long countCarriageReturn(URL dataFile) throws Exception {
@qchaupds just curious, when we do content validation, aren't we using this ByteBuffer then as well? In which case, doesn't this mean we are now going through and reading in the entire file multiple times? Could we combine this with content validation? It seems like if we have to open up the actual product to get some information (e.g. record size), then that could be considered in the realm of content validation.

2021-04-28 04:05 UTC, jordanpadams requested changes

2021-04-28 04:05 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/objectAccess/TableReader.java
> +            this.recordSize = this.countCarriageReturn(dataFile);
@qchaupds per our convo today and [this ticket](https://github.com/NASA-PDS/validate/issues/325), I don't think this method will work in the event the CRLF is embedded within a record. we should consider checking for record count using opencsv when we are already reading in the data to do content validation.

2021-05-02 17:19 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/objectAccess/TableReader.java
> +            this.recordSize = this.countCarriageReturn(dataFile);
from @qchaupds The code change in TableReader.java in pds4-jparser now uses the record length to calculate the number of records.  No need to read the file.

2021-05-03 20:01 UTC, jordanpadams requested changes

2021-05-03 20:01 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/objectAccess/TableReader.java
> +        LOGGER.debug("getRecordSize:adapter {}",adapter);
@qchaupds hate to nitpick here again, but can we fix the whitespace here and elsewhere in your code updates to lineup all the tabs correctly for better readability?

2021-05-03 20:52 UTC, jordanpadams commented on src/main/java/gov/nasa/pds/objectAccess/TableReader.java
> +            while (reader.readLine() != null) linesInBuffer++;
per email from @qchaupds 

per the middle of the line question, The buffer is a chunk of a file up to so many bytes.  That chunk is given to the parseBufferForLineCount().  The function returns the number of lines read via readLine().   Once that first chunk is done, the next part of the file is then fetched into another chunk.
 
The regression tests fortunately catches any mis-counting of the number of records.

per the `readline` question, the documentation says it handles both cases well.
 
https://docs.oracle.com/javase/8/docs/api/java/io/BufferedReader.html#readLine--
 
public String readLine()
                throws IOException
Reads a line of text. A line is considered to be terminated by any one of a line feed ('\n'), a carriage return ('\r'), or a carriage return followed immediately by a linefeed.

2021-05-03 21:08 UTC, jordanpadams approved these changes

2021-05-03 21:08 UTC, merged